# -*- coding: utf-8 -*-
"""combine_papers_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3tJlufvcmZw9GJCS4Bv4nZ1W_6sLVBB
"""

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

ACM=pd.read_csv('/content/drive/MyDrive/Title_filtering/ACM_prefilter.csv')
Springer=pd.read_csv('/content/drive/MyDrive/Title_filtering/Springer_prefilter.csv')
GS=pd.read_csv('/content/drive/MyDrive/Title_filtering/GS_prefilter.csv')
DBLP=pd.read_csv('/content/drive/MyDrive/Title_filtering/DBLP_prefilter.csv')
IEEE=pd.read_csv('/content/drive/MyDrive/Title_filtering/IEEE_prefilter.csv')

# modify df to contain only title, url, author, year, and venue
ACM=ACM[['title', 'url', 'authors', 'year', 'conference']]
Springer=Springer[['title', 'url', 'authors', 'year', 'conference']]
IEEE=IEEE[['Document Title', 'PDF Link', 'Authors', 'Publication Year', 'Publication Title']]
GS=GS[['title', 'PDF', 'authors', 'year', 'conference']]
DBLP=DBLP[['title', 'url', 'author', 'year', 'booktitle']]

#modify the column names of each df
column_names=['title','url/pdf','authors','year','venue']
ACM.columns=column_names
Springer.columns=column_names
IEEE.columns=column_names
GS.columns=column_names
DBLP.columns=column_names

#combine all the papers together
Combined_papers=pd.concat([ACM,Springer,IEEE,GS,DBLP], ignore_index=True)
len(Combined_papers)#before removing duplicates: 3995 match with the sum of each individual record

#remove duplicates
Combined_papers['title_lower']=Combined_papers['title'].str.lower()
Combined_papers.drop_duplicates(subset=['title_lower'], inplace=True)
Combined_papers.drop(columns=['title_lower'], inplace=True)
len(Combined_papers)#after duplicate removing we have 3882

Combined_papers.head()

Combined_papers.to_excel('/content/drive/MyDrive/Title_filtering/Combined_Papers.xlsx', index=False)