# -*- coding: utf-8 -*-
"""title_filter_code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13l8M9L-N-FqWAaUz7dHpSnVXwuZhEfKP
"""

import numpy as np
import pandas as pd
import string

from google.colab import drive
drive.mount('/content/drive')

#ACM=pd.read_csv('/content/drive/MyDrive/Title_filtering/ACM_prefilter.csv')
#Springer=pd.read_csv('/content/drive/MyDrive/Title_filtering/Springer_prefilter.csv')
#GS=pd.read_csv('/content/drive/MyDrive/Title_filtering/GS_prefilter.csv')
#BDLP=pd.read_csv('/content/drive/MyDrive/Title_filtering/DBLP_prefilter.csv')
#IEEE=pd.read_csv('/content/drive/MyDrive/Title_filtering/IEEE_prefilter.csv')
Combined_papers=pd.read_csv('/content/drive/MyDrive/Title_filtering/Combined_papers_prefilter.csv')

search_terms = (['trust', 'distrust', 'trustworthiness','trustworthy', 'software engineering'
                  , 'deep learning', 'machine learning', 'llm', 'llms',
                 'language model', 'language models', 'gpt'])

def filter(df):
  df['contain_keyword']=False
  df['title_lower']=df['title'].str.lower()
  for index, title in enumerate(df['title_lower']):
    for term in search_terms:
      if term in title:
          df.loc[index, 'contain_keyword'] = True

  df.drop(columns=['title_lower'], inplace=True)
  return df

filter(Combined_papers).to_csv('/content/drive/MyDrive/Title_filtering/Combined_papers_filtered.csv', index=False)

filter(ACM).to_excel('/content/drive/MyDrive/Title_filtering/ACM_filtered.xlsx', index=False)

filter(Springer).to_excel('/content/drive/MyDrive/Title_filtering/Springer_filtered.xlsx', index=False)

filter(GS).to_excel('/content/drive/MyDrive/Title_filtering/GS_filtered.xlsx', index=False)

filter(BDLP).to_excel('/content/drive/MyDrive/Title_filtering/BDLP_filtered.xlsx', index=False)

#IEEE's variable name is different
  def filter(df):
  df['contain_keyword']=False
  df['title_lower']=df['Document Title'].str.lower()
  for index, title in enumerate(df['title_lower']):
    for term in search_terms:
      if term in title:
          df.loc[index, 'contain_keyword'] = True

  df.drop(columns=['title_lower'], inplace=True)
  return df
filter_IEEE(IEEE).to_excel('/content/drive/MyDrive/Title_filtering/IEEE_filtered.xlsx', index=False)